---
packages:
  - 'packages/*'
  - 'packages/plugins/*'
  - 'packages/integrations/*'
  - 'packages/platforms/*'

catalog:
  "debug": "^4.3.4"
  "tsup": "^8.2.4"
  "typescript": "^5.5.4"
  "lodash-es": "^4.17.21"
  "vite-node": "^2.0.5"
  "vitest": "^2.0.5"
  "@types/debug": "^4.1.12"
  "@types/lodash-es": "^4.17.12"
  "@types/node": "^20.14.11"
