---
packages:
  # all direct children of packages/
  - 'packages/*'
  # all children of packages/plugins
  - 'packages/plugins/*'
  # all children of packages/integrations
  - 'packages/integrations/*'
