---
packages:
  - 'packages/*'
  - 'packages/plugins/*'
  - 'packages/integrations/*'
  - 'packages/platforms/*'

catalog:
  "base64-arraybuffer": "^1.0.2"
  "debug": "^4.3.4"
  "kleur": "^4.1.5"
  "lodash-es": "^4.17.21"
  "modern-async": "^2.0.4"
  "svgo": "^3.2.0"
  "tsup": "^8.2.4"
  "typescript": "^5.5.4"
  "vite": "^5.4.6"
  "vite-node": "^2.1.2"
  "vitest": "^2.1.2"
  "@dagrejs/graphlib": "^2.2.4"
  "@types/debug": "^4.1.12"
  "@types/lodash-es": "^4.17.12"
  "@types/node": "^20.14.11"
