[build]
command = "pnpm --filter \"@dmno/signup-api\" run build"

[functions]
directory = "packages/signup-api/functions-dist"

[dev]
autoLaunch = false

[[redirects]]
from = "/*"
to = "/.netlify/functions/:splat"
status = 200


# setting NODE_ENV to production will make netlify not install dev dependencies
# which we need for the build...
[context.production]
DMNO_ENV = "production"

[context.deploy-preview.environment]
DMNO_ENV = "staging"
