[build]
publish = "packages/docs-site/dist"
command = "pnpm --filter \"@dmno/docs-site\" run netlify-build"

[[redirects]]
from = "/docs"
to = "/"
status = 302

[[redirects]]
from = "/docs/"
to = "/"
status = 302
