<template>
  <div>
    <h1>Example vite-powered web app! {{ OTHER_ITEM }}</h1>
    <h2>Config item from dmno config: {{ randomNumFromEnv }}</h2>
    <!-- <h2>Config item from DMNO_CONFIG: {{ rewrittenVal }}</h2> -->
    <p>The above is a random number generated by DMNO. It should change each time you restart vite</p>
  </div>
</template>

<script setup lang="ts">
// import { DMNO_CONFIG } from '@dmno/core';

// import '../.dmno/dmno-config';

// NOTE - using `import.meta.env.XXX` doesnt work within vue templates
// so we have to pull it into a variable here first
const randomNumFromEnv = DMNO_PUBLIC_CONFIG.VITE_RANDOM_NUM;

const OTHER_ITEM = DMNO_PUBLIC_CONFIG.DMNO_ENV;


</script>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
  transition: filter 300ms;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
