# thanks to https://github.com/systeminit/si/blob/main/.github/workflows/community-check.yml

name: Label community PR

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check-is-community:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    env:
      DMNO_STAFF: "theoephraim philmillman"
    steps:
      - name: Check PR author
        id: check_author
        run: |
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          if ! [[ "${DMNO_STAFF}" =~ "$PR_AUTHOR" ]]; then
            echo "Authored by DMNO community member!"
            echo "requires-community-tag=true" >> $GITHUB_OUTPUT
          else
            echo "Authored by DMNO staff"
          fi
      - name: Label PR 
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.pull_request.number }},
              labels: [ steps.check_author.outputs.requires-community-tag && 'community' && 'staff' ]
            });
