# thanks to https://github.com/systeminit/si/blob/main/.github/workflows/community-check.yml

name: Label community PR

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check-is-community:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    env:
      # pre-approved maintainers list (dmno staff)
      MAINTAINERS_LIST: "theoephraim philmillman"
    steps:
      - name: Check PR author
        id: check_author
        run: |
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          if [[ "${MAINTAINERS_LIST}" =~ "$PR_AUTHOR" ]]; then
            echo "Authored by pre-approved maintainer"
            echo "official-maintainer=true" >> $GITHUB_OUTPUT
          else
            echo "Authored by DMNO community member!"
          fi
      - name: Label PR 
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ github.event.pull_request.number }},
              labels: [ {{ steps.check_author.outputs.official-maintainer && 'maintainer' || 'community' }} ]
            });
